"""Generated media: download, index, serve.

The upstream returns signed URLs that expire on the order of hours.  A caller who
wanted to keep an image found in a chat would be reaching for a dead link, so
anything generated is pulled down and served locally by id.

Two details are not negotiable:

- **The id, not the path, is what gets served.**  The HTTP layer mounts the
  directory under ``/media/`` and *only* id-shaped names resolve to a file, so
  ``..`` in a URL never reaches the filesystem.  Symlinks fail for the same
  reason: a link named ``<id>.png`` is refused rather than followed.
- **Downloading never fails a request.**  A chat that produced text and an image
  should not fail because the file server was slow — the markdown link stays
  pointed at the signed URL and a failed download is recorded on the audit row.
"""

from __future__ import annotations

import asyncio
import os
import re
import time
from pathlib import Path
from typing import Any

import httpx

from . import upstream
from .records import MediaItem, MEDIA_IMAGE

# Media ids are only ever generated by security.new_id, but a URL is not: a name
# from outside is checked against exactly this shape before it is joined to a path.
_ID_PATTERN = re.compile(r"^[A-Za-z0-9_-]{8,64}$")

# A single file larger than this is refused rather than streamed to disk.
_MAX_FILE_BYTES = 32 * 1024 * 1024

# The extension of a download is guessed from the URL when it declares one.
_EXTENSIONS = {
    "image/png": ".png",
    "image/jpeg": ".jpg",
    "image/webp": ".webp",
    "image/gif": ".gif",
    "video/mp4": ".mp4",
}
_SUFFIXES = ("", *_EXTENSIONS.values())


class MediaStore:
    """Owns the generated-media directory."""

    def __init__(self, db: Any, settings_fn: Any) -> None:
        self._db = db
        self._settings_fn = settings_fn
        self._dir: Path | None = None

    # ------------------------------------------------------------------ paths

    def root(self) -> Path:
        settings = self._settings_fn()
        return Path(settings.media.generated_dir or "./generated")

    def ensure_dir(self) -> Path:
        if self._dir is None:
            self._dir = self.root()
            self._dir.mkdir(parents=True, exist_ok=True)
        return self._dir

    def path_for(self, media_id: str) -> Path | None:
        """Resolve a media id to a file, refusing anything that is not one.

        The stored name carries a suffix that was guessed at download time, so an
        id alone is not a filename: both forms, and only those two, are tried.
        """
        if not _ID_PATTERN.match(media_id or ""):
            return None
        base = self.ensure_dir()
        plain = base / media_id
        # Both checks matter: the id shape keeps traversal out, and the symlink
        # check stops a planted link from escaping the directory.
        if plain.is_file() and not plain.is_symlink():
            return plain
        for candidate in sorted(base.glob(f"{media_id}.*")):
            if candidate.is_file() and not candidate.is_symlink():
                return candidate
        # Nothing on disk: the console indexes an item that was never downloaded,
        # or was pruned, and a 404 is the honest answer.
        return None

    def public_url(self, media_id: str) -> str:
        """The URL a caller should be shown for this item."""
        base = (self._settings_fn().media.public_base_url or "").strip().rstrip("/")
        if base:
            return f"{base}/{media_id}"
        return f"/media/{media_id}"

    # -------------------------------------------------------------- downloads

    async def download(
        self,
        source_url: str,
        *,
        kind: str = MEDIA_IMAGE,
        prompt: str = "",
        model: str = "",
        account_name: str = "",
    ) -> MediaItem | None:
        """Pull a generated asset down and index it.  Never raises.

        The whole body is read into memory before it touches the disk, because
        the size cap has to mean something: a file that turns out to be too large
        must not already be halfway written.
        """
        from .security import new_id

        media_id = new_id()
        try:
            settings = self._settings_fn()
            timeout = httpx.Timeout(connect=10.0, read=60.0, write=10.0, pool=10.0)
            kwargs: dict[str, Any] = {"timeout": timeout, "follow_redirects": True}
            proxy = (settings.upstream.proxy or "").strip()
            if proxy:
                host = upstream.urlsplit(source_url).hostname or ""
                if not upstream.is_loopback(host):
                    kwargs["proxy"] = proxy
            async with httpx.AsyncClient(**kwargs) as client:
                response = await client.get(source_url)
                if response.status_code >= 400:
                    return None
                body = await response.aread()
                if len(body) > _MAX_FILE_BYTES:
                    return None
        except (httpx.HTTPError, OSError, asyncio.TimeoutError, ValueError):
            # A refused download is a fact about the file, not about the request:
            # the caller keeps the upstream's URL and the audit row records why.
            return None

        suffix = _suffix_for(source_url, response.headers.get("content-type", ""))
        path = self.ensure_dir() / f"{media_id}{suffix}"
        try:
            await asyncio.to_thread(path.write_bytes, body)
        except OSError:
            return None

        item = MediaItem(
            id=media_id,
            kind=kind,
            url=self.public_url(media_id),
            source_url=source_url,
            prompt=prompt[:2000],
            model=model,
            account_name=account_name,
            created_at=time.time(),
        )
        await self._db.add_media(item)
        await self.prune()
        return item

    # ---------------------------------------------------------------- pruning

    async def prune(self) -> int:
        """Keep the directory under the configured ceiling; report deletions.

        The ceiling is on bytes, not files, so it deletes however many oldest
        files the cap requires instead of a fixed number.
        """
        items = await self._db.list_media(limit=10_000)
        if not items:
            return 0
        ceiling = max(64, self._settings_fn().media.max_total_size_mb) * 1024 * 1024
        base = self.ensure_dir()
        sizes: list[tuple[float, str, int]] = []
        for item in items:
            path = base / item.id
            for suffix in _SUFFIXES:
                candidate = base / f"{item.id}{suffix}"
                if candidate.is_file():
                    path = candidate
                    break
            try:
                size = path.stat().st_size
            except OSError:
                continue
            sizes.append((item.created_at, item.id, size))

        total = sum(size for _, _, size in sizes)
        # Newest first: the ones worth deleting are at the other end.
        sizes.sort(key=lambda entry: entry[0])
        removed = 0
        for _, media_id, size in sizes:
            if total <= ceiling:
                break
            await self.delete(media_id)
            total -= size
            removed += 1
        return removed

    async def delete(self, media_id: str) -> bool:
        item = await self._db.delete_media(media_id)
        if item is None:
            return False
        base = self.ensure_dir()
        for suffix in _SUFFIXES:
            candidate = base / f"{media_id}{suffix}"
            if candidate.is_symlink() or candidate.is_file():
                try:
                    candidate.unlink()
                except OSError:
                    return False
        return True

    def total_size(self) -> int:
        try:
            return sum(
                entry.stat().st_size for entry in self.ensure_dir().iterdir() if entry.is_file()
            )
        except OSError:
            return 0


def _suffix_for(url: str, content_type: str) -> str:
    """Guess a file's extension, preferring what the URL says.

    A stripped suffix question ("image.png?sign=…") is common on CDNs, and the
    content-type is only a fallback — a wrong one is how a png ends up named
    ``.jpeg``.
    """
    from urllib.parse import urlsplit

    path = urlsplit(url).path
    if "." in path.rsplit("/", 1)[-1]:
        suffix = os.path.splitext(path.rsplit("/", 1)[-1])[1].lower()
        if suffix and len(suffix) <= 6:
            return suffix
    return _EXTENSIONS.get(content_type.split(";")[0].strip(), ".bin")
